### ISSUE TITLE
第二次选择图片后，获取的还是上一次的图片文件

### ISSUE THREAD

**Issue by chenxi1991** [yaochangliang159/ChoosePicture#1]

**Comment by yaochangliang159** [comment]
对啊，每次选择图片，我会将图片保存到SD卡下的ycl/temp_headImg.jpg，如果你第二次选择图片，路径还是和第一张图片一样，只不过第二次的图片把第一次的图片覆盖了，图片名字是一样的，但是内容不一样了

**Comment by chenxi1991** [comment]
找到原因了。。。 图片有变化 但是文件路径没变化 我是用的glide加载 因为路径名称一模一样 glide就没重新加载图片了

**Comment by yaochangliang159** [comment]
。。。。。好吧
