### ISSUE TITLE
在项目中两个地方用到了这个工程使用过程中有bug

### ISSUE THREAD

**Issue by chenxi1991** [yaochangliang159/ChoosePicture#2]
我在fragmenA中使用用于上传美图 在activityB中使用用于上传头像，先在activityB中使用正常回调获取图片，再在fragmentA中使用，会执行到activityB中实现的回调方法，此时activityB是已经被finish掉的

**Comment by yaochangliang159** [comment]
注意，在Fragment中，应该这样进行第二步：

 new UpLoadHeadImageDialog(getActivity(),MyFragment.this).show();

**Comment by chenxi1991** [comment]
我看了你dialog的源码 ，在fragment中直接调用如下方法YCLTools.getInstance().startChoose(PictureMainFragment.this, which);

**Comment by chenxi1991** [comment]
换用库中的dialog 调用方法如你所说 还是有这个问题
